removing legacy fields
refractionPOINT/lc-extension pull request #111
Opened 2024-02-29 19:42 UTC by oklex

1. removing legacy fields
2. simplifying comments
3. re-locating supported_actions

2024-02-29 19:53 UTC, maximelb requested changes
Can you remove it from schema.py line 47 and add it to schema.py line 7 too?

2024-02-29 21:53 UTC, maximelb approved these changes

2024-02-29 22:28 UTC, josh-lc approved these changes

2024-02-29 22:36 UTC, maximelb approved these changes

2024-03-01 00:05 UTC, merged

2024-03-21 16:08 UTC, josh-lc reviewed
LGTM